### ISSUE TITLE
Suggestion: cache results

### ISSUE THREAD

**Issue by chrismessina** [nathangathright/alfred-producthunt-search#6]
Might it make sense to cache results to speed up responsiveness? Maybe expire cache after a month, or add a command to refresh the cache?

**Comment by nathangathright** [comment]
The Algolia Node API makes it really easy to implement an [InMemoryCache](https://www.algolia.com/doc/api-client/advanced/configure-the-client/javascript/?language=javascript#cache-on-requests-and-responses):
> With `InMemoryCache`, the client stores both requests and responses in memory. When you perform the same query again during your search session, the client reads the results from the requests cache instead of firing a new search request. This avoids useless or duplicate API calls, which can happen, for example, when a user deletes characters from their current query. Similarly, the client retrieves results from the response cache for queries that you’ve already performed during your search session.
